name: Deploy React App with .env.dev Configuration

on:
  workflow_dispatch:

permissions:
  id-token: write
  statuses: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Setup .env File
        run: cp .env.dev .env

      - name: Build
        run: npm run build

      - name: Echo .env contents
        run: cat .env

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::${{ env.REACT_APP_AWS_IAM }}:role/GithubActionsS3Role
          role-session-name: S3PublishPackage
          role-duration-seconds: 900

      - name: Check login
        run: aws sts get-caller-identity

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://${{ env.REACT_APP_BUCKET }}
