name: Deploy React App with .env.dev Configuration

on:
  workflow_dispatch:

permissions:
  id-token: write
  statuses: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Setup .env File
        run: cp .env.dev .env

      - name: Build
        run: npm run build

      - name: Echo .env contents
        run: cat .env
